[package]
name = "rust-attohttpc"
version = "0.1.0"
edition = "2021"

[dependencies]
attohttpc = { version = "0.25.0", default-features = false }

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1
strip = true
